// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt2HcI8NcbWW2HG6EirLYusNJQk_qwZbs',
    appId: '1:1094967881036:web:f4ec6286f644d52361f3e9',
    messagingSenderId: '1094967881036',
    projectId: 'alaeesh-7198f',
    authDomain: 'alaeesh-7198f.firebaseapp.com',
    storageBucket: 'alaeesh-7198f.firebasestorage.app',
    measurementId: 'G-HFY1HWCT01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB8ea1wRGx3e2TQXzWpyqirEQ5BzfZuFQ',
    appId: '1:1094967881036:android:34450cf49dbb6ded61f3e9',
    messagingSenderId: '1094967881036',
    projectId: 'alaeesh-7198f',
    storageBucket: 'alaeesh-7198f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVygReXzEOpzmyqaBooU9td5wEsmjbZIw',
    appId: '1:1094967881036:ios:84f9bbc9f7ee381e61f3e9',
    messagingSenderId: '1094967881036',
    projectId: 'alaeesh-7198f',
    storageBucket: 'alaeesh-7198f.firebasestorage.app',
    androidClientId: '1094967881036-2m3jhe55q80b65i03umlo6l8n34j1ntd.apps.googleusercontent.com',
    iosClientId: '1094967881036-7q73umpftkak4v8b76fkjurho9f9djro.apps.googleusercontent.com',
    iosBundleId: 'com.alaeeesh.alaeeeesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVygReXzEOpzmyqaBooU9td5wEsmjbZIw',
    appId: '1:1094967881036:ios:84f9bbc9f7ee381e61f3e9',
    messagingSenderId: '1094967881036',
    projectId: 'alaeesh-7198f',
    storageBucket: 'alaeesh-7198f.firebasestorage.app',
    androidClientId: '1094967881036-2m3jhe55q80b65i03umlo6l8n34j1ntd.apps.googleusercontent.com',
    iosClientId: '1094967881036-7q73umpftkak4v8b76fkjurho9f9djro.apps.googleusercontent.com',
    iosBundleId: 'com.alaeeesh.alaeeeesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt2HcI8NcbWW2HG6EirLYusNJQk_qwZbs',
    appId: '1:1094967881036:web:674ecab7743cc8a561f3e9',
    messagingSenderId: '1094967881036',
    projectId: 'alaeesh-7198f',
    authDomain: 'alaeesh-7198f.firebaseapp.com',
    storageBucket: 'alaeesh-7198f.firebasestorage.app',
    measurementId: 'G-92PH8VHYMJ',
  );
}
